make:
	  g++ -c main.cpp ConnectFourAbstract.cpp ConnectFourPlus.cpp ConnectFourPlusUndo.cpp ConnectFourDiag.cpp Cell.cpp GameCreator.cpp --std=c++11
	  g++ -o exe main.o ConnectFourAbstract.o ConnectFourPlus.o ConnectFourPlusUndo.o ConnectFourDiag.o Cell.o GameCreator.o
 
clean:
	  rm *.o exe
