make:
	  g++ -c _mainTester.cpp CPU.cpp CPUProgram.cpp StringHelper.cpp Memory.cpp Computer.cpp --std=c++11
	  g++ -o exe _mainTester.o CPU.o CPUProgram.o StringHelper.o Memory.o Computer.o
 
clean:
	  rm *.o exe
